[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.default.fuzz]
runs = 256
max_test_rejects = 65536

[rpc_endpoints]
monad_mainnet = "${MONAD_MAINNET_RPC}"
monad_testnet = "${MONAD_TESTNET_RPC}"

[etherscan]
monad = { key = "${MONAD_EXPLORER_KEY}", url = "https://explorer.monad.xyz/api" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
